sudo: true
language: c
compiler:
    - gcc
os:
    - linux
before_install:
install:
        - ./autogen.sh
        - mkdir build
        - cd build
        - ../configure --prefix=`pwd`/../install/
        - make
        - make install
script:
        - cd ../install
        - cd bin
        - ./piver
        - ./pinative -t 16 -s 100 -f 100
        - ./piagent -c 10 &
        - ./piproxy -a 127.0.0.1 -t 16 -s 100 -f 100
notifications:
    email:
        recipients:
            - ddeboni@sandia.gov
        on_success: [change]
        on_failure: [always] 
