#!/bin/sh

path=.
name=teller
ipprefix=10.54.21

lower=0
upper=-1

port=1
samp=1
freq=100

while getopts n:p:i:l:u:t:s:f: opt
do
	case "${opt}"
	in
		p) path=${OPTARG};;
		n) name=${OPTARG};;
		i) ipprefix=${OPTARG};;
		l) lower=${OPTARG};;
		u) upper=${OPTARG};;
		t) port=${OPTARG};;
		s) samp=${OPTARG};;
		f) freq=${OPTARG};;
		\?) echo "Usage: $0 [-l lowerbound] [-u upperbound] [-t sensorport] [-s samples] [-f frequency]";;
	esac
done

for ((node=$lower; node<=$upper; ++node))
do
	echo "Collecting $samp samples from $name-pm$node to $path/$name$node.out"
	./proxy -a $ipprefix.$node -t $port -s $samp -f $freq > $path/$name$node.out &
done


