#!/bin/sh

export LOGFILE="/mnt/log/`hostname`.log"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/power/lib

if [ -z "$1" ]
then
    FREQ=10
else
    FREQ=$1
fi

while true
do
    if pgrep piagent 1>/dev/null;then
        sleep 1
    else
       ./piagent -c $FREQ&
    fi
done
