#!/bin/sh

LOGFILE=`hostname`.log

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/power/lib

while true
do
    if pgrep piagent 1>/tmp/$LOGFILE;then
        sleep 1
    else
       ./piagent 1> /tmp/$LOGFILE &
    fi
done
