.\" Manpage for piproxy
.\" Contact ddeboni@sandia.gov to correct errors or typos
.TS man 8 "28 May 2014" "1.2" "piproxy man page"
.SH NAME
piproxy \- communicate with PowerInsight device
.SH SYNOPSIS
\fBpiproxy\fP [ -a \fIsa_addr\fP ] [ -p \fIsa_port\fP ]
[ -t \fIsensorport\fP ] [ -s \fIsamples\fP ] [ -f \fIfrequency\fP ]
[ -m \fImark\fP ] [ -l ] [ -c ] [ -r ] [ -v ] [ -i ] [ -h ]
.SH DESCRIPTION
\fBpiproxy\fP is a command line utility for communicating monitor
and control commands to the PowerInsight embedded device
.SH OPTIONS
.TP
\fB-a\fP [ \fIsa_addr\fP ]
IP address of PowerInsight device (default is localhost)
\fB-p\fP [ \fIsa_port\fP ]
TCP/IP port of PowerInsight agent (default is 20201)
\fB-t\fP [ \fIsensorport\fP ]
sensor port to be used (default is CPU=1)
\fB-d\fP [ \fIsamples\fP ]
number of samples to collect (default is 1, 0 for infinite)
\fB-f\fP [ \fIfrequency\fP ]
frequency of collection (default is 1Hz, 0 for off)
\fB-m\fP [ \fImark\fP ]
add marker message to the agent log
\fB-l\fP
control agent logger (uses port and frequency)
\fB-c\fP
read counter values (uses port)
\fB-r\fP
reset counter values to zero (uses port)
\fB-v\fP
verbosity of results
\fB-i\fP
information regarding version and build
\fB-h\fP
usage information
.SH "SEE ALSO"
pilogger (8)
.SH BUGS
No known bugs.
.SH AUTHOR
David DeBonis (ddeboni@sandia.gov)
