#!/usr/bin/perl -w

use strict;

my $num = shift;
    defined($num) or die "Must provide agent number to log\n";
my $port = shift;

if ($num < 10) { $num = "0" . $num; }
system("ssh root\@teller-pm$num tail -f /var/tmp/teller-pm$num.log");

