#!/bin/bash

echo "Pt#	  A	  V	  mA	  mV	  mW"
for port in 1 2 3 4 5 6 7
do
    let "A = $RANDOM % 8192"
    let "V = $RANDOM % 8192"
    let "mA = $RANDOM % 5000 + 3000"
    let "mV = $RANDOM % 11000 + 3000"
    let "mW = A * V"

    echo -e "$port,\t $A,\t $V,\t $mA,\t $mV,\t $mW,\t "
done
