#!/usr/bin/perl -w

use strict;

my $start = shift;
    defined($start) or die "Must provide first agent in range\n";
my $fin = shift;
    defined($fin) or die "Must provide last agent in range\n";
my $action = shift or die "Must provide action for agent (start|stop)\n";
my $port;
$port = shift or do {
    !defined($port) and $port = 20202;
};
my $sensorport;
$sensorport = shift or do {
    !defined($sensorport) and $sensorport = 8;
};

print "sending control command to teller-pm$start through " .
      "teller-pm$fin for port(s) $sensorport\n";

for my $num ($start..$fin) {
    if ($num < 10) { $num = "0" . $num; }
    system("../control.pl -h teller-pm$num -p $port -c $action -v $sensorport &");
}

