#!/usr/bin/perl -w

use strict;

my $start = shift or die "Must provide first agent in range\n";
my $fin = shift or die "Must provide last agent in range\n";

print "killing agents on teller-pm$start through teller-pm$fin\n";

my $ret;
for my $num ($start..$fin) {
    if ($num < 10) { $num = "0" . $num; }
    system("ssh teller-pm$num /home/power/script/scripts/agent_kill &");
}
sleep(2);
