#!/usr/bin/perl -w

use strict;

my $start = shift or die "Must provide first client in range\n";
my $fin = shift or die "Must provide last client in range\n";

print "checking clients on teller-pm$start through teller-pm$fin\n";

my $count=1;
print "\n Greater than 0 returns mean client(s) is/are running\n";
for ($start..$fin) {
    system("ssh teller-pm$_ ps auxw|grep client.pl|grep -v grep|wc -l &");
    $count++;
}
sleep(2);
