#!/usr/bin/perl -w

use strict;

my $start = shift;
    defined($start) or die "Must provide first client in range\n";
my $fin = shift;
    defined($fin) or die "Must provide last client in range\n";

print "checking clients on teller-pm$start through teller-pm$fin\n";

my $count=1;
print "\n Greater than 0 returns mean client(s) is/are running\n";
for my $num ($start..$fin) {
    if ($num < 10) { $num = "0" . $num; }
    system("ssh teller-pm$num ps auxw|grep client.pl|grep -v grep|wc -l &");
    $count++;
}
sleep(2);
