#!/usr/bin/perl -w

use strict;

my $start = shift or die "Must provide first client in range\n";
my $fin = shift or die "Must provide last client in range\n";
my $action = shift or die "Must provide action for client (start|stop)\n";
my $port;
$port = shift or do {
    !defined($port) and $port = 8;
};

print "sending control command to teller-pm$start through " .
      "teller-pm$fin for port(s) $port\n";

for ($start..$fin) {
    system("../control.pl -h teller-pm$_ -c $action -v $port &");
}

