#!/usr/bin/perl -w

use strict;

my $start = shift or die "Must provide first client in range\n";
my $fin = shift or die "Must provide last client in range\n";

print "killing clients on teller-pm$start through teller-pm$fin\n";

my $ret;
for my $num ($start..$fin) {
    if ($num < 10) { $num = "0" . $num; }
    system("ssh teller-pm$num ./client_kill &");
}
sleep(2);
