#!/usr/bin/perl -w

use strict;

my $start = shift or die "Must provide first client in range\n";
my $fin = shift or die "Must provide last client in range\n";
my $interval = 1;
#$interval = shift or warn "Interval not specified using 1 second\n";

print "starting clients on teller-pm$start through teller-pm$fin" .
      "interval $interval\n";

my $ret;
for ($start..$fin) {
    print "teller-pm$_\n";
    $ret = `ssh teller-pm$_ ./client_start $interval`;

}
