#!/usr/bin/perl -w

use strict;

my $start = shift or die "Must provide first client in range\n";
my $fin = shift or die "Must provide last client in range\n";
my $interval;
$interval = shift or do {
    !defined($interval) and $interval = 1;
};

print "starting clients on teller-pm$start through teller-pm$fin " .
      "interval $interval\n";

my $ret;
for ($start..$fin) {
    print "teller-pm$_ interval $interval\n";
    system("ssh teller-pm$_ ./client_start $interval &");

}
