#!/usr/bin/perl -w

use strict;

my $start = shift;
    defined($start) or die "Must provide first agent in range\n";
my $fin = shift;
    defined($fin) or die "Must provide last agent in range\n";

print "checking teller-pm$start through teller-pm$fin\n";

my $count=1;
for my $num ($start..$fin) {
    if ($num < 10) { $num = "0" . $num; }
    print "teller-pm$num:\n";
    system("ssh root\@teller-pm$num ps aux | grep ./piagent");
    $count++;
}
sleep(2);
