#!/usr/bin/perl -w

use strict;

my $start = shift;
    defined($start) or die "Must provide first agent in range\n";
my $fin = shift;
    defined($fin) or die "Must provide last agent in range\n";

print "checking pi$start through pi$fin\n";

my $count=1;
for my $num ($start..$fin) {
    if ($num < 10) { $num = "0" . $num; }
    print "pi$num:\n";
    system("ssh root\@pi$num ps aux | grep ./piagent");
    $count++;
}
sleep(2);
